export const PAYMENT_PROCCESS_FAIL = 'PAYMENT_PROCCESS_FAIL';
export const PAYMENT_PROCCESS_SUCCESS = 'PAYMENT_PROCCESS_SUCCESS';
export const PAYMENT_PROCCESS_REQUEST = 'PAYMENT_PROCCESS_REQUEST';
export const PAYMENT_PROCCESS_RESET = 'PAYMENT_PROCCESS_REQUEST';


export const PAYMENT_DATA_FAIL = 'PAYMENT_DATA_FAIL';
export const PAYMENT_DATA_SUCCESS = 'PAYMENT_DATA_SUCCESS';
export const PAYMENT_DATA_REQUEST = 'PAYMENT_DATA_REQUEST';
export const PAYMENT_DATA_RESET = 'PAYMENT_DATA_REQUEST';


export const CLEAR_ERRORS = 'CLEAR_ERRORS';